name: Playwright
on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: e2e
        run: npm install

      - name: Install Playwright browsers
        working-directory: e2e
        run: npx playwright install --with-deps

      - name: Run tests
        working-directory: e2e
        env:
          APP_URL: ${{ secrets.APP_URL }}           # optional for now
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}     # optional for now
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}  # optional for now
        run: npx playwright test

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: e2e/playwright-report
